services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=https://www.whiskarz.com/
      - NODE_ENV=production
    restart: always